@WebApplicationAPI_HostAddress = https://localhost:7173

POST {{WebApplicationAPI_HostAddress}}/api/user

###

@id=99
GET {{WebApplicationAPI_HostAddress}}/api/user/{{id}}

###

GET {{WebApplicationAPI_HostAddress}}/api/user/{{id}}

###
